spring:
  application:
    name: building-management-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/building_management?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root  # o root si no creaste usuario específico
    password: Freekmans32!  # o tu password de root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # IMPORTANTE: usar none para que Flyway controle la BD
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.buildingmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# JWT Configuration
app:
  jwt:
    secret: ${JWT_SECRET:1d71c0430abf3e6b5fe6d2fcd7148a74c84606c58063736037b05fdb75935af252c1313eafb5fdf65d1d762151836f143786aea7a1e9c9d0e73bac9908943849}
    expiration: 86400000 # 24 horas en milisegundos
    refresh-expiration: 604800000 # 7 días en milisegundos

  # File Storage Configuration
  file:
    upload-dir: ${FILE_UPLOAD_DIR:./uploads}
    max-size: 10MB
    allowed-extensions: pdf,jpg,jpeg,png,doc,docx,xls,xlsx

  # CORS Configuration
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.buildingmanagement: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: WARN
    com.buildingmanagement: INFO